apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "base-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "base-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "base-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "base-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          env:
            {{- toYaml (.Values.env | default list) | nindent 12 }}
          {{- if .Values.configSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.configSecret }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml (.Values.resources | default dict) | nindent 12 }}

