name: CI - Build & Test Services

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build payment-service
        working-directory: services/payment-service
        run: mvn -B -q test package

      - name: Build order-service
        working-directory: services/order-service
        run: mvn -B -q test package

      - name: Build fraud-service
        working-directory: services/fraud-service
        run: mvn -B -q test package

